# Site
repository: noriakis/cv
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Packages
title: Helping the transcriptome analysis
website: github.com/noriakis/cv

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: facespics
github_username:  noriakis
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
# about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  <mark>R</mark>
  <mark>Python</mark>

content:
  - title: Packages
    layout: text
    content: | 
      <center>CBNplot</center>
      <center>
        <div style="
        background-image: url('https://github.com/noriakis/software/blob/main/images/CBNplot_readme_3.png?raw=true');
        background-size: 500px 500px;
        background-position: 400px;
        width: 200px;
        height: 200px;
        border-radius: 100%;
        border: solid 0.5em rgba(144, 144, 144, 0.5);">
       </div>
      </center>
      <br>
      <center>wcGeneSummary</center>
      <center>
        <div style="
        background-image: url('https://github.com/noriakis/wcGeneSummary/blob/main/images/erccWc.png?raw=true');
        background-size: 500px 500px;
        background-position: 360px;
        width: 200px;
        height: 200px;
        border-radius: 100%;
        border: solid 0.5em rgba(144, 144, 144, 0.5);">
       </div>
    </center>
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
